name: CI
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          components: clippy, rustfmt
          override: true

      - name: update Rust
        run: make install
      - name: Install Clippy
        run: rustup component add clippy

      - name: lint
        run: make lint
      - name: format
        run: make format
      - name: test
        run: make test

      - name: Build in release mode
        run: cargo build --release

      - name: Upload binary as artifact
        uses: actions/upload-artifact@v2
        with:
          name: optimized-binary
          path: 
